### ISSUE TITLE
NoClassDefFoundError: ZipUnArchiver

### ISSUE THREAD

**Issue by OLibutzki** [maybeec/oomph-task-unzip#8]
The following exception is thrown at setup task execution:

```
Bundle com.github.maybeec.oomph.task.unzip 1.0.0.201610121435
Bundle org.eclipse.oomph.setup 1.6.0.v20160920-0456, build=2617, branch=2d2865a4ea3642019005845421c65b1a0d87c679
Bundle org.eclipse.oomph.setup.core 1.6.0.v20160920-1303, build=2617, branch=2d2865a4ea3642019005845421c65b1a0d87c679
Bundle org.eclipse.oomph.setup.maven 1.6.0.v20160920-0456, build=2617, branch=2d2865a4ea3642019005845421c65b1a0d87c679
Bundle org.eclipse.oomph.setup.p2 1.6.0.v20160920-0456, build=2617, branch=2d2865a4ea3642019005845421c65b1a0d87c679
Performing unzip
Starting Unzip process
Archive: C:\Projekte\IDE\tapir-showcase-latest\ws\tapir-showcase.zip
Destination: tapir-showcase
java.lang.NoClassDefFoundError: org/codehaus/plexus/archiver/zip/ZipUnArchiver
  at com.github.maybeec.oomph.task.unzip.core.impl.UnzipUtilImpl.getUnArchiver(UnzipUtilImpl.java:65)
  at com.github.maybeec.oomph.task.unzip.core.impl.UnzipUtilImpl.unzip(UnzipUtilImpl.java:28)
  at com.github.maybeec.oomph.task.unzip.impl.unzipTaskImpl.perform(unzipTaskImpl.java:310)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3131)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3074)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4295)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4289)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4287)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3065)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3040)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2940)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:556)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:682)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by themetalone** [comment]
This is caused by #7 . Rolled back to the last stable version. 

I haven't thought anybody besides us would actually use the task now ^^ I apologize for any inconveniences

**Comment by OLibutzki** [comment]
Nevermind, the task just does what I've been looking for, so I decided to try it.
